apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app_name }}
  ports:
  - port: {{ .Values.ports.port }}
    targetPort: {{ .Values.ports.containerPort }}